version: '3.8'
services:
  web:
    build: .
    container_name: cena-web-server
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: cena-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
volumes:
  db_data: